### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by LastChanceBilly** [The-Chris-Davies/SAEelectricpedal#1]
Important:
- [x] Implement non-volatile storage using SD card modules (pedal.calibrate(), error logging, etc)
- [ ] Add Watchdog timer!
- [ ] Integrate CAN BUS modules (use builtin CAN controller with interface circuit, or SPI CAN adapter)
- [ ] Make error detection smarter (not just one good read to reset timer - percentage good reads per sec to not fail?)
- [ ] Add startup condition to catch bad reset / watchdog (system state flag + must read acc value to start - add shutdown state)
- [ ] Add Ready To Drive pin that activates sound

Useful Changes:
- [x] Read values from both sensors
- [x] Add Error handling to Pedal.read()
     - [x] Timer for 100ms after an error - see reference doc [here](https://www.st.com/content/ccc/resource/technical/document/reference_manual/59/b9/ba/7f/11/af/43/d5/CD00171190.pdf/files/CD00171190.pdf/jcr:content/translations/en.CD00171190.pdf), pg. 336/494 and [here](https://github.com/rogerclarkmelbourne/Arduino_STM32/blob/master/STM32F1/cores/maple/HardwareTimer.h)
     - [x] should the error range be within 10% of the linear pot value?
- [x] Replace serial with interrupt-controlled exit in Pedal.calibrate()
- [ ] Use shorts or ints instead of bytes, for higher resolution
- [x] Generate acceptable tolerance in Pedal::Pedal()
- [ ] Add interpolation in Pedal.calibrate()
- [x] add dead zone (to both sides?) so pedal has full range of 0-100% throttle (currently ~5% to ~95%)
- [x] short and open-circuit protection (if values are below mini-err / above maxi+err)
- [x] Find a return value for Pedal::read() error
- [ ] Replace digitalRead() calls with homebrew solution
